name: "Go test coverage checker"
description: "Check test coverage"
author: "@walkersumida"
branding:
  icon: "code"
  color: "yellow"
inputs:
  path:
    description: "target path"
    default: "./..."
    required: false
  threshold:
    description: "total coverage threshold"
    default: "80"
    required: false
  logLevel:
    description: "`error` or `info`"
    default: "error"
    required: false
  slackWebhookUrl:
    description: ""
    default: ""
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
